num1=int(input("please enter a first number") )
num2=int(input("please enter a second number"))
print(float (num1)+7)
print(str(num2)+"3")
print(num1+num2)
print(num1%num2)
print(num1-num2)
print(num1*num2)
print(num1<num2)
print(num1>num2)
