print("gamargoba mainteresebs romeli mshobeli upro didia deda tu mama?")
user_age1 = input("ramdeni wlisaa dedaseni? ")
user_age2 = input("ramdeni wlisaa mamaseni? ")
print(user_age1,user_2)
print("tu iqneba fols esegi dedaseni ufro didia da tu true esegi47 mamaseni")