#name=input("enter your name")
#surname=input("enter your surname") 
#age=input("enter your age")  
#print("my name is  ",name,"my surname is",surname,"my age is",age) 

num1=int(input("please enter a first number"))
num2=int(input("please enter a second number"))
print(float(num1)+3)
print(str(num2)+"5")
print(num1*num2)
print(num1%num2)
print(num1+num2)
print(num1-num2)